# Generated by Django 5.1.3 on 2025-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=100)),
                ('horarios', models.TextField(help_text=' Ej: 07:00, 08:00, cada 15 minutos....')),
                ('tarifa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
