# Generated by Django 5.1.3 on 2025-06-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='tarifa',
        ),
        migrations.AddField(
            model_name='horario',
            name='tarifa_adulto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarifa Adulto'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tarifa_escolar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarifa Escolar'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tarifa_mayor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarifa Adulto Mayor'),
        ),
    ]
